### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jjt**
Add MetaLab requirements/instructions

### CODE REVIEW

**Comment by izaakschroeder** [comment]
Recommend adding `brew` to the list.

**Comment by izaakschroeder** [comment]
`npm start` is usually reserved for running _the_ server (i.e. real server) and not the dev one; maybe `npm run dev` instead.

**Comment by jjt** [comment]
I don't know if we can assume OSX, but adding it is probably good.

Good call on `npm run dev`.

**Comment by jjt** [comment]
Closed in favour of https://github.com/sendwithus/startupslam/pull/10

**Pull request closed without merging**
